### ISSUE TITLE
Store is unable to import products

### ISSUE THREAD

**Issue by HeshamIsmail** [Knawat/knawat-dropshipping-magento2#92]
**Describe the bug**
The user is unable to import products from Knawat.

**To Reproduce**
-Go to Magento2 admin store.
2-Click on Dropshing ->Settings.
3-Add Consumer and secret key then save
4-Go Dropshing ->Product import.

**Result**: The user becomes unable to import any products.

**Expected Result**: Store gets the ability to import products normally.

**Troubleshooting steps**:

1-User reinstalled and reconfigured Knawat extension on Magento2 but still unable to import products.

**Attachments**:

1-Screenshot showing the import page

![image](https://user-images.githubusercontent.com/74185849/117972997-7c4ca080-b334-11eb-88ce-e3431d768ebb.png)
![image](https://user-images.githubusercontent.com/74185849/117973018-87073580-b334-11eb-977d-4c327b33bbb1.png)

**Enviroment (please complete the following information):**
 - OS: Cpanel
 - Browser: Google chrome
 - Plugin Version :1.0.10
 - Magento Version: 2.3.5-p1

**Comment by jayjittv** [comment]
@HeshamIsmail @HazemKhaled @iamdharmesh 
I checked this issue and reproduced this case with 2.3.5  
 1.0.10 release has some major issue/blockers like 
 1) Product attribute with options has not been created due to magento core file changes and that stop the import process(https://github.com/Knawat/knawat-dropshipping-magento2/commit/0ef9f4e49f07baa16586bc1382854b9d2eb4c75e#diff-a47aba0365f0141d11649475dcc7ae46766d1a1a6edf8521f2ef56f4de3556f8)
 2) Sometimes images are not being imported (https://github.com/Knawat/knawat-dropshipping-magento2/commit/37ff8b6a1214faeb13a7e6261c16e8a18d397bc3#diff-a47aba0365f0141d11649475dcc7ae46766d1a1a6edf8521f2ef56f4de3556f8)
 
 Above issues has been fixed after 1.0.10 release and available in current master branch . So, you can test that branch code and for version release we need to release new version

**Comment by HeshamIsmail** [comment]
The issue for this store in specific was handled by DEV, the two fixes will still be tested
